name: deeprl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=17.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.11.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - annotated-types==0.7.0
      - box2d-py==2.3.5
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - chex==0.1.89
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - docstring-parser==0.16
      - etils==1.12.2
      - farama-notifications==0.0.4
      - ffmpeg==1.4
      - filelock==3.18.0
      - flax==0.10.6
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - gymnasium==1.1.1
      - humanize==4.12.3
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jax==0.6.2
      - jaxlib==0.6.2
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - nest-asyncio==1.6.0
      - networkx==3.5
      - numpy==2.3.1
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.16
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - proglog==0.1.12
      - protobuf==6.31.1
      - psutil==7.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.4
      - rich==14.0.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shtab==1.7.2
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - swig==4.3.1
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.75
      - toolz==1.0.0
      - torch==2.7.1
      - tqdm==4.67.1
      - treescope==0.1.9
      - typeguard==4.4.4
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tyro==0.9.24
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.20.1
      - werkzeug==3.1.3
      - zipp==3.23.0

